# Generated by Django 5.0.4 on 2024-05-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavor',
            old_name='color',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='flavor',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='flavor',
            old_name='name',
            new_name='Flavor',
        ),
    ]
