# Generated by Django 5.0.4 on 2024-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0002_rename_color_flavor_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='Rating',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flavor',
            name='Flavor',
            field=models.CharField(max_length=50),
        ),
    ]
