# Generated by Django 5.0.4 on 2024-05-06 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellybeans', '0003_flavor_rating_alter_flavor_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='Rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
